<?php

use Illuminate\Database\Seeder;

class PlanTableSeeder extends Seeder
{

    //產品數量
    const PLAN_NUM = 10;

    public function run()
    {


        //AXA供應商添加產品

                //HealthVital Series (Non-HK$ Policy) Start
                factory(App\Plan::class)->create([
                    'plan_category_id' => 1,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Insurance – 10 Years',
                    'code' => 'HVMII10',
                    'term' => '10 years',
                    'requirement' => 'requirement',
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.495,
                    'rate_1_basic' => 0.495,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.495,
                    'rate_2_override' => 0.13,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.495,
                    'rate_3_override' => 0.02,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.495,
                    'rate_4_override' => 0.02,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.495,
                    'rate_5_override' => 0.02,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.495,
                    'rate_6_override' => 0.02,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.495,
                    'rate_7_override' => 0.02,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.495,
                    'rate_8_override' => 0.02,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.495,
                    'rate_9_override' => 0.02,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.495,
                    'rate_10_override' => 0.07,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 1,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Insurance – 15 Years',
                    'code' => 'HVMII15',
                    'term' => '15 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.66,
                    'rate_1_basic' => 0.66,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.66,
                    'rate_2_override' => 0.27,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.66,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.66,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.66,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.66,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.66,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.66,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.66,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.66,
                    'rate_10_override' => 0.11,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 1,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Insurance – 20 Years',
                    'code' => 'HVMII20',
                    'term' => '20 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.825,
                    'rate_1_basic' => 0.825,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.825,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.825,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.825,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.825,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.825,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.825,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.825,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.825,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.825,
                    'rate_10_override' => 0.15,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 1,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Insurance – 25 Years',
                    'code' => 'HVMII25',
                    'term' => '25 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.843,
                    'rate_1_basic' => 0.843,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.843,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.843,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.843,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.843,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.843,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.843,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.843,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.843,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.843,
                    'rate_10_override' => 0.16,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);
                 //HealthVital Series (Non-HK$ Policy) End

                 //HealthVital Series (HK$ Policy) Start
                factory(App\Plan::class)->create([
                    'plan_category_id' => 2,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Insurance – 10 Years',
                    'code' => 'HVMII10',
                    'term' => '10 years',
                    'requirement' => 'requirement',
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.55,
                    'rate_1_basic' => 0.55,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.55,
                    'rate_2_override' => 0.13,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.55,
                    'rate_3_override' => 0.02,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.55,
                    'rate_4_override' => 0.02,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.55,
                    'rate_5_override' => 0.02,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.55,
                    'rate_6_override' => 0.02,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.55,
                    'rate_7_override' => 0.02,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.55,
                    'rate_8_override' => 0.02,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.55,
                    'rate_9_override' => 0.02,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.55,
                    'rate_10_override' => 0.07,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 2,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Insurance – 15 Years',
                    'code' => 'HVMII15',
                    'term' => '15 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.733,
                    'rate_1_basic' => 0.733,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.733,
                    'rate_2_override' => 0.27,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.733,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.733,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.733,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.733,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.733,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.733,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.733,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.733,
                    'rate_10_override' => 0.11,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 2,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Insurance – 20 Years',
                    'code' => 'HVMII20',
                    'term' => '20 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.917,
                    'rate_1_basic' => 0.917,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.917,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.917,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.917,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.917,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.917,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.917,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.917,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.917,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.917,
                    'rate_10_override' => 0.15,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 2,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Insurance – 25 Years',
                    'code' => 'HVMII25',
                    'term' => '25 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.953,
                    'rate_1_basic' => 0.953,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.953,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.953,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.953,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.953,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.953,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.953,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.953,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.953,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.953,
                    'rate_10_override' => 0.16,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);
                 //HealthVital Series (HK$ Policy) End

                //Supplement or Rider Start
                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Multiple Benefit – 10 Years',
                    'code' => 'HVMIMB10',
                    'term' => '10 years',
                    'requirement' => 'requirement',
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.642,
                    'rate_1_basic' => 0.642,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.642,
                    'rate_2_override' => 0.13,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.642,
                    'rate_3_override' => 0.02,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.642,
                    'rate_4_override' => 0.02,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.642,
                    'rate_5_override' => 0.02,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.642,
                    'rate_6_override' => 0.02,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.642,
                    'rate_7_override' => 0.02,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.642,
                    'rate_8_override' => 0.02,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.642,
                    'rate_9_override' => 0.02,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.642,
                    'rate_10_override' => 0.07,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Multiple Benefit – 15 Years',
                    'code' => 'HVMIMB15',
                    'term' => '15 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.825,
                    'rate_1_basic' => 0.825,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.825,
                    'rate_2_override' => 0.27,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.825,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.825,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.825,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.825,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.825,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.825,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.825,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.825,
                    'rate_10_override' => 0.11,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Multiple Benefit – 20 Years',
                    'code' => 'HVMIMB20',
                    'term' => '20 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.99,
                    'rate_1_basic' => 0.99,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.99,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.99,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.99,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.99,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.99,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.99,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.99,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.99,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.99,
                    'rate_10_override' => 0.15,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Multiple Benefit – 25 Years',
                    'code' => 'HVMIMB25',
                    'term' => '25 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.99,
                    'rate_1_basic' => 0.99,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.99,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.99,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.99,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.99,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.99,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.99,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.99,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.99,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.99,
                    'rate_10_override' => 0.16,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Major Illness Multiple Benefit – Pay to age 85',
                    'code' => 'HVMIMBP85',
                    'term' => '25 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.99,
                    'rate_1_basic' => 0.99,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.99,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.99,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.99,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.99,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.99,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.99,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.99,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.99,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.99,
                    'rate_10_override' => 0.16,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Early Stage Major Illness Benefit – 10 Years',
                    'code' => 'HVESMIB10',
                    'term' => '10 years',
                    'requirement' => 'requirement',
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.642,
                    'rate_1_basic' => 0.642,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.642,
                    'rate_2_override' => 0.13,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.642,
                    'rate_3_override' => 0.02,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.642,
                    'rate_4_override' => 0.02,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.642,
                    'rate_5_override' => 0.02,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.642,
                    'rate_6_override' => 0.02,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.642,
                    'rate_7_override' => 0.02,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.642,
                    'rate_8_override' => 0.02,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.642,
                    'rate_9_override' => 0.02,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.642,
                    'rate_10_override' => 0.07,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Early Stage Major Illness Benefit – 15 Years',
                    'code' => 'HVESMIB15',
                    'term' => '15 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.825,
                    'rate_1_basic' => 0.825,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.825,
                    'rate_2_override' => 0.27,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.825,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.825,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.825,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.825,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.825,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.825,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.825,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.825,
                    'rate_10_override' => 0.11,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Early Stage Major Illness Benefit – 20 Years',
                    'code' => 'HVESMIB20',
                    'term' => '20 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.99,
                    'rate_1_basic' => 0.99,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.99,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.99,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.99,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.99,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.99,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.99,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.99,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.99,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.99,
                    'rate_10_override' => 0.15,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Early Stage Major Illness Benefit – 25 Years',
                    'code' => 'HVESMIB25',
                    'term' => '25 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.99,
                    'rate_1_basic' => 0.99,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.99,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.99,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.99,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.99,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.99,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.99,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.99,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.99,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.99,
                    'rate_10_override' => 0.16,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'HealthVital Early Stage Major Illness Benefit – Pay to age 85',
                    'code' => 'HVESMIBP85',
                    'term' => '25 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.99,
                    'rate_1_basic' => 0.99,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.99,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.99,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.99,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.99,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.99,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.99,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.99,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.99,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.99,
                    'rate_10_override' => 0.16,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);

                factory(App\Plan::class)->create([
                    'plan_category_id' => 3,
                    'provider_id' => 1,
                    'name' => 'Early Stage Major Illness Benefit II – Pay to age 85',
                    'code' => 'ESMIBP85',
                    'term' => '25 years',
                    //虛擬數據
                    'requirement' => 'requirement',
                    //虛擬數據
                    'description' => 'cut off around 15 each month, pay date around 20th each month',
                    'rate_monthly' => 0,
                    'rate_yearly' => 0.99,
                    'rate_1_basic' => 0.99,
                    'rate_1_override' => 0,
                    'rate_1_bonus' => 0,
                    'rate_2_basic' => 0.99,
                    'rate_2_override' => 0.33,
                    'rate_2_bonus' => 0,
                    'rate_3_basic' => 0.99,
                    'rate_3_override' => 0.05,
                    'rate_3_bonus' => 0,
                    'rate_4_basic' => 0.99,
                    'rate_4_override' => 0.05,
                    'rate_4_bonus' => 0,
                    'rate_5_basic' => 0.99,
                    'rate_5_override' => 0.07,
                    'rate_5_bonus' => 0,
                    'rate_6_basic' => 0.99,
                    'rate_6_override' => 0.07,
                    'rate_6_bonus' => 0,
                    'rate_7_basic' => 0.99,
                    'rate_7_override' => 0.07,
                    'rate_7_bonus' => 0,
                    'rate_8_basic' => 0.99,
                    'rate_8_override' => 0.07,
                    'rate_8_bonus' => 0,
                    'rate_9_basic' => 0.99,
                    'rate_9_override' => 0.07,
                    'rate_9_bonus' => 0,
                    'rate_10_basic' => 0.99,
                    'rate_10_override' => 0.16,
                    'rate_10_bonus' => 0,
                    'annual_premium' => 10000,
                ]);
                 //Supplement or Rider End



        //HealthSelect Series (Non-HK$ Policy) Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 4,
            'provider_id' => 1,
            'name' => 'HealthSelect Major Illness Insurance – 20 Years',
            'code' => 'HSMII20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.825,
            'rate_1_basic' => 0.825,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.825,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.825,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.825,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.825,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.825,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.825,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.825,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.825,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.825,
            'rate_10_override' => 0.15,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 4,
            'provider_id' => 1,
            'name' => 'HealthSelect Major Illness Insurance – 25 Years',
            'code' => 'HSMII25',
            'term' => '25 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.843,
            'rate_1_basic' => 0.843,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.843,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.843,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.843,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.843,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.843,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.843,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.843,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.843,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.843,
            'rate_10_override' => 0.16,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //HealthVital Series (Non-HK$ Policy) End


        //HealthSelect Series (HK$ Policy) Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 5,
            'provider_id' => 1,
            'name' => 'HealthSelect Major Illness Insurance – 20 Years',
            'code' => 'HSMII20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.917,
            'rate_1_basic' => 0.917,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.917,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.917,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.917,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.917,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.917,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.917,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.917,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.917,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.917,
            'rate_10_override' => 0.15,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 5,
            'provider_id' => 1,
            'name' => 'HealthSelect Major Illness Insurance – 25 Years',
            'code' => 'HSMII25',
            'term' => '25 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.953,
            'rate_1_basic' => 0.953,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.953,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.953,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.953,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.953,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.953,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.953,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.953,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.953,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.953,
            'rate_10_override' => 0.16,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //HealthSelect Series (HK$ Policy) End

        //Supplement or Rider Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 6,
            'provider_id' => 1,
            'name' => 'Major Illness Multiple Benefit II – 20 Years',
            'code' => 'MIMBII20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.99,
            'rate_1_basic' => 0.99,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.99,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.99,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.99,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.99,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.99,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.99,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.99,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.99,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.99,
            'rate_10_override' => 0.15,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 6,
            'provider_id' => 1,
            'name' => 'Major Illness Multiple Benefit II – 25 Years',
            'code' => 'MIMBII25',
            'term' => '25 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.99,
            'rate_1_basic' => 0.99,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.99,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.99,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.99,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.99,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.99,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.99,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.99,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.99,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.99,
            'rate_10_override' => 0.16,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 6,
            'provider_id' => 1,
            'name' => 'Major Illness Multiple Benefit II – Pay to age 85',
            'code' => 'MIMBII85',
            'term' => '25 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.99,
            'rate_1_basic' => 0.99,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.99,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.99,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.99,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.99,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.99,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.99,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.99,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.99,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.99,
            'rate_10_override' => 0.16,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 6,
            'provider_id' => 1,
            'name' => 'Early Stage Major Illness Benefit II – 20 Years',
            'code' => 'ESMIBII20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.99,
            'rate_1_basic' => 0.99,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.99,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.99,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.99,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.99,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.99,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.99,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.99,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.99,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.99,
            'rate_10_override' => 0.15,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 6,
            'provider_id' => 1,
            'name' => 'Early Stage Major Illness Benefit II – 25 Years',
            'code' => 'ESMIBII25',
            'term' => '25 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.99,
            'rate_1_basic' => 0.99,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.99,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.99,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.99,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.99,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.99,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.99,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.99,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.99,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.99,
            'rate_10_override' => 0.16,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 6,
            'provider_id' => 1,
            'name' => 'Early Stage Major Illness Benefit II – Pay to age 85',
            'code' => 'ESMIBII85',
            'term' => '25 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.99,
            'rate_1_basic' => 0.99,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.99,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.99,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.99,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.99,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.99,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.99,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.99,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.99,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.99,
            'rate_10_override' => 0.16,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //Supplement or Rider End


        //HealthElite Critical Illness Insurance Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 7,
            'provider_id' => 1,
            'name' => 'HealthElite Critical Illness Insurance – 10 Years',
            'code' => 'HECII10',
            'term' => '10 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.55,
            'rate_1_basic' => 0.55,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.55,
            'rate_2_override' => 0.13,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.55,
            'rate_3_override' => 0.02,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.55,
            'rate_4_override' => 0.02,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.55,
            'rate_5_override' => 0.02,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.55,
            'rate_6_override' => 0.02,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.55,
            'rate_7_override' => 0.02,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.55,
            'rate_8_override' => 0.02,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.55,
            'rate_9_override' => 0.02,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.55,
            'rate_10_override' => 0.07,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 7,
            'provider_id' => 1,
            'name' => 'HealthElite Critical Illness Insurance – 15 Years',
            'code' => 'HECII15',
            'term' => '15 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.733,
            'rate_1_basic' => 0.733,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.733,
            'rate_2_override' => 0.27,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.733,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.733,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.733,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.733,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.733,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.733,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.733,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.733,
            'rate_10_override' => 0.11,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 7,
            'provider_id' => 1,
            'name' => 'HealthElite Critical Illness Insurance – 20 Years',
            'code' => 'HECII20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.917,
            'rate_1_basic' => 0.917,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.917,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.917,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.917,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.917,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.917,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.917,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.917,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.917,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.917,
            'rate_10_override' => 0.15,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 7,
            'provider_id' => 1,
            'name' => 'HealthElite Critical Illness Insurance – 25 Years',
            'code' => 'HECII25',
            'term' => '25 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.953,
            'rate_1_basic' => 0.953,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.953,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.953,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.953,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.953,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.953,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.953,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.953,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.953,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.953,
            'rate_10_override' => 0.16,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //HealthElite Critical Illness Insurance End


        //Supplement or Rider Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 8,
            'provider_id' => 1,
            'name' => 'HealthElite Enhanced Benefit Supplement – 10 Years',
            'code' => 'HEEBS10',
            'term' => '10 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.642,
            'rate_1_basic' => 0.642,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.642,
            'rate_2_override' => 0.13,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.642,
            'rate_3_override' => 0.02,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.642,
            'rate_4_override' => 0.02,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.642,
            'rate_5_override' => 0.02,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.642,
            'rate_6_override' => 0.02,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.642,
            'rate_7_override' => 0.02,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.642,
            'rate_8_override' => 0.02,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.642,
            'rate_9_override' => 0.02,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.642,
            'rate_10_override' => 0.07,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 8,
            'provider_id' => 1,
            'name' => 'HealthElite Enhanced Benefit Supplement – 15 Years',
            'code' => 'HEEBS15',
            'term' => '15 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.825,
            'rate_1_basic' => 0.825,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.825,
            'rate_2_override' => 0.27,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.825,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.825,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.825,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.825,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.825,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.825,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.825,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.825,
            'rate_10_override' => 0.11,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 8,
            'provider_id' => 1,
            'name' => 'HealthElite Enhanced Benefit Supplement – 20 Years',
            'code' => 'HEEBS20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.99,
            'rate_1_basic' => 0.99,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.99,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.99,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.99,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.99,
            'rate_5_override' => 0.07,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.99,
            'rate_6_override' => 0.07,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.99,
            'rate_7_override' => 0.07,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.99,
            'rate_8_override' => 0.07,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.99,
            'rate_9_override' => 0.07,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.99,
            'rate_10_override' => 0.15,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //Supplement or Rider End


        //Fortune Guard Life Insurance (Non-HK$ Policy) Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 9,
            'provider_id' => 1,
            'name' => 'Fortune Guard Life Insurance – 10 Years',
            'code' => 'FGLI10',
            'term' => '10 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.55,
            'rate_1_basic' => 0.55,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.55,
            'rate_2_override' => 0.11,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.55,
            'rate_3_override' => 0.02,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.55,
            'rate_4_override' => 0.02,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.55,
            'rate_5_override' => 0.02,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.55,
            'rate_6_override' => 0,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0,
            'rate_7_override' => 0,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0,
            'rate_8_override' => 0,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 9,
            'provider_id' => 1,
            'name' => 'Fortune Guard Life Insurance – 15 Years',
            'code' => 'FGLI15',
            'term' => '15 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.733,
            'rate_1_basic' => 0.733,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.733,
            'rate_2_override' => 0.27,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.733,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.733,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.733,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.733,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.733,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.733,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 9,
            'provider_id' => 1,
            'name' => 'Fortune Guard Life Insurance – 20 Years',
            'code' => 'FGLI20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.953,
            'rate_1_basic' => 0.953,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.953,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.953,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.953,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.953,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.953,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.953,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.953,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.953,
            'rate_9_override' => 0.05,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.953,
            'rate_10_override' => 0.05,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 9,
            'provider_id' => 1,
            'name' => 'Fortune Guard Life Insurance – Pay to age 100',
            'code' => 'FGLIP100',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.953,
            'rate_1_basic' => 0.953,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.953,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.953,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.953,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.953,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.953,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.953,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.953,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.953,
            'rate_9_override' => 0.05,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.953,
            'rate_10_override' => 0.05,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //Fortune Guard Life Insurance (Non-HK$ Policy) End


        //Fortune Guard Life Insurance (HK$ Policy) Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 10,
            'provider_id' => 1,
            'name' => 'Fortune Guard Life Insurance – 10 Years',
            'code' => 'FGLI10',
            'term' => '10 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.513,
            'rate_1_basic' => 0.513,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.513,
            'rate_2_override' => 0.11,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.513,
            'rate_3_override' => 0.02,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.513,
            'rate_4_override' => 0.02,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.513,
            'rate_5_override' => 0.02,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0,
            'rate_6_override' => 0,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0,
            'rate_7_override' => 0,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0,
            'rate_8_override' => 0,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 10,
            'provider_id' => 1,
            'name' => 'Fortune Guard Life Insurance – 15 Years',
            'code' => 'FGLI15',
            'term' => '15 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.697,
            'rate_1_basic' => 0.697,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.697,
            'rate_2_override' => 0.27,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.697,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.697,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.697,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.697,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.697,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.697,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 10,
            'provider_id' => 1,
            'name' => 'Fortune Guard Life Insurance – 20 Years',
            'code' => 'FGLI20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.917,
            'rate_1_basic' => 0.917,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.917,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.917,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.917,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.917,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.917,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.917,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.917,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.917,
            'rate_9_override' => 0.05,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.917,
            'rate_10_override' => 0.05,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 10,
            'provider_id' => 1,
            'name' => 'Fortune Guard Life Insurance – Pay to age 100',
            'code' => 'FGLIP100',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.917,
            'rate_1_basic' => 0.917,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.917,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.917,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.917,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.917,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.917,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.917,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.917,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.917,
            'rate_9_override' => 0.05,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.917,
            'rate_10_override' => 0.05,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //Fortune Guard Life Insurance (HK$ Policy) End

        //Supplement or Rider Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 11,
            'provider_id' => 1,
            'name' => 'Fortune Guard Accident Protector – 10 Years',
            'code' => 'FGAP10',
            'term' => '10 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.55,
            'rate_1_basic' => 0.55,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.55,
            'rate_2_override' => 0.11,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.55,
            'rate_3_override' => 0.02,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.55,
            'rate_4_override' => 0.02,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.55,
            'rate_5_override' => 0.02,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0,
            'rate_6_override' => 0,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0,
            'rate_7_override' => 0,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0,
            'rate_8_override' => 0,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 11,
            'provider_id' => 1,
            'name' => 'Fortune Guard Accident Protector – 15 Years',
            'code' => 'FGAP15',
            'term' => '15 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.733,
            'rate_1_basic' => 0.733,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.733,
            'rate_2_override' => 0.27,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.733,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.733,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.733,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.733,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.733,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.733,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 11,
            'provider_id' => 1,
            'name' => 'Fortune Guard Accident Protector – 20 Years',
            'code' => 'FGAP20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.953,
            'rate_1_basic' => 0.953,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.953,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.953,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.953,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.953,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.953,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.953,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.953,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.953,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.953,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 11,
            'provider_id' => 1,
            'name' => 'Fortune Guard Accident Protector – Pay to age 85',
            'code' => 'FGAPP85',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.953,
            'rate_1_basic' => 0.953,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.953,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.953,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.953,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.953,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.953,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.953,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.953,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.953,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.953,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //Supplement or Rider End

        //Fortune Protector Life Insurance (Non-HK$ Policy) Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 12,
            'provider_id' => 1,
            'name' => 'Fortune Protector Life Insurance – 10 Years',
            'code' => 'FPLI10',
            'term' => '10 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.495,
            'rate_1_basic' => 0.495,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.495,
            'rate_2_override' => 0.11,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.495,
            'rate_3_override' => 0.02,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.495,
            'rate_4_override' => 0.02,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.495,
            'rate_5_override' => 0.02,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0,
            'rate_6_override' => 0,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0,
            'rate_7_override' => 0,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0,
            'rate_8_override' => 0,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 12,
            'provider_id' => 1,
            'name' => 'Fortune Protector Life Insurance – 15 Years',
            'code' => 'FPLI15',
            'term' => '15 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.678,
            'rate_1_basic' => 0.678,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.678,
            'rate_2_override' => 0.27,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.678,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.678,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.678,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.678,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.678,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.678,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 12,
            'provider_id' => 1,
            'name' => 'Fortune Protector Life Insurance – 20 Years',
            'code' => 'FPLI20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.88,
            'rate_1_basic' => 0.88,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.88,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.88,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.88,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.88,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.88,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.88,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.88,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.88,
            'rate_9_override' => 0.05,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.88,
            'rate_10_override' => 0.05,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 12,
            'provider_id' => 1,
            'name' => 'Fortune Protector Life Insurance – Pay to age 100',
            'code' => 'FPLIP100',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.88,
            'rate_1_basic' => 0.88,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.88,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.88,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.88,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.88,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.88,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.88,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.88,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.88,
            'rate_9_override' => 0.05,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.88,
            'rate_10_override' => 0.05,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //Fortune Protector Life Insurance (Non-HK$ Policy) End


        //Fortune Protector Life Insurance (HK$ Policy) Start
        factory(App\Plan::class)->create([
            'plan_category_id' => 13,
            'provider_id' => 1,
            'name' => 'Fortune Protector Life Insurance – 10 Years',
            'code' => 'FPLI10',
            'term' => '10 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.477,
            'rate_1_basic' => 0.477,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.477,
            'rate_2_override' => 0.11,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.477,
            'rate_3_override' => 0.02,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.477,
            'rate_4_override' => 0.02,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.477,
            'rate_5_override' => 0.02,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0,
            'rate_6_override' => 0,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0,
            'rate_7_override' => 0,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0,
            'rate_8_override' => 0,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 13,
            'provider_id' => 1,
            'name' => 'Fortune Protector Life Insurance – 15 Years',
            'code' => 'FPLI15',
            'term' => '15 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.642,
            'rate_1_basic' => 0.642,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.642,
            'rate_2_override' => 0.27,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.642,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.642,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.642,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.642,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.642,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.642,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0,
            'rate_9_override' => 0,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0,
            'rate_10_override' => 0,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 13,
            'provider_id' => 1,
            'name' => 'Fortune Protector Life Insurance – 20 Years',
            'code' => 'FPLI20',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.843,
            'rate_1_basic' => 0.843,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.843,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.843,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.843,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.843,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.843,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.843,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.843,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.843,
            'rate_9_override' => 0.05,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.843,
            'rate_10_override' => 0.05,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);

        factory(App\Plan::class)->create([
            'plan_category_id' => 13,
            'provider_id' => 1,
            'name' => 'Fortune Protector Life Insurance – Pay to age 100',
            'code' => 'FPLIP100',
            'term' => '20 years',
            'requirement' => 'requirement',
            'description' => 'cut off around 15 each month, pay date around 20th each month',
            'rate_monthly' => 0,
            'rate_yearly' => 0.843,
            'rate_1_basic' => 0.843,
            'rate_1_override' => 0,
            'rate_1_bonus' => 0,
            'rate_2_basic' => 0.843,
            'rate_2_override' => 0.33,
            'rate_2_bonus' => 0,
            'rate_3_basic' => 0.843,
            'rate_3_override' => 0.05,
            'rate_3_bonus' => 0,
            'rate_4_basic' => 0.843,
            'rate_4_override' => 0.05,
            'rate_4_bonus' => 0,
            'rate_5_basic' => 0.843,
            'rate_5_override' => 0.05,
            'rate_5_bonus' => 0,
            'rate_6_basic' => 0.843,
            'rate_6_override' => 0.05,
            'rate_6_bonus' => 0,
            'rate_7_basic' => 0.843,
            'rate_7_override' => 0.05,
            'rate_7_bonus' => 0,
            'rate_8_basic' => 0.843,
            'rate_8_override' => 0.05,
            'rate_8_bonus' => 0,
            'rate_9_basic' => 0.843,
            'rate_9_override' => 0.05,
            'rate_9_bonus' => 0,
            'rate_10_basic' => 0.843,
            'rate_10_override' => 0.05,
            'rate_10_bonus' => 0,
            'annual_premium' => 10000,
        ]);
        //Fortune Protector Life Insurance (HK$ Policy) End

    }
}
